[build]
  command = "bun run test"
  publish = "public"

[[edge_functions]]
  path = "/*"
  excludedPath = ["/og.png", "/og/*", "/.netlify/images"]
  function = "server"
[functions]
  included_files = ["netlify/functions/assets/**", "public/assets/icons/**"]
